config/routes.rb
Rails.application.routes.draw do
  resources :chats
  get 'reviews/new'
  get 'reviews/create'
  resources :orders, only: [:new, :create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { sessions: 'sessions' }
  root 'pages#home'
  get 'pages/delivery'
  get 'pages/rules'
  get 'pages/contacts'
  get 'pages/about'
  get 'pages/message'
  resources :feedback, only: [:create]

    # config/routes.rb
    resources :orders do
      member do
        patch 'cancel' # маршрут для отмены заказа
      end
    end

    # config/routes.rb
    resources :orders do
      member do
    get 'extend' # маршрут для продления заказа
  end
end

get 'reviews', to: 'reviews#index'

resources :orders do
  resource :review, only: [:new, :create]
end

get 'profile', to: 'profiles#show', as: :profile

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike.rb
class Bike < ApplicationRecord
  has_many :orders

  enum status: { free: "Свободен", busy: "Занят" }

  def update_status
    if orders.completed.exists?
      update(status: :free)
    else
      update(status: :busy)
    end
  end

  enum bike_type: {
    mountain: "горный",
    urban: "городской",
    urban_economy: "городской эконом",
    carbon: "карбон"
  }

  def self.ransackable_attributes(auth_object = nil)
    super + %w(status)
  end

  def self.ransackable_associations(auth_object = nil)
    super + %w(orders)
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/feedback.rb
# app/models/feedback.rb
class Feedback < ApplicationRecord
  enum status: { unprocessed: 0, processed: 1 }

  before_validation :set_default_status, on: :create
  before_validation :set_user_info, on: :create, if: :user_signed_in?

  validates :name, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10}\z/, message: "must be 10 digits" }

  private

  def set_default_status
    self.status ||= :unprocessed
  end

  def set_user_info
    self.name ||= current_user.name if current_user.name.present?
    self.phone_number ||= current_user.phone_number if current_user.phone_number.present?
  end
end

app/models/horizont.rb
class Horizont < ApplicationRecord
	def self.ransackable_attributes(auth_object = nil)
	    ["created_at", "description", "id", "img", "title", "updated_at"]
	  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_and_belongs_to_many :bikes
  belongs_to :user
  has_one :review

  enum admin_status: { in_processing: "В обработке", in_progress: "Выполняется", delivering: "Доставляется", completed: "Завершено", cancel: "Отменено" }
  enum status: { pay: "Оплачено", no_pay: "Не оплачено" }

  after_create :update_bike_status

  def update_bike_status
    self.bikes.each do |bike|
      if self.completed?
        bike.update(status: :free)
      else
        bike.update(status: :busy)
      end
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "delivery_address", "end_date", "id", "return_address", "start_date", "status", "updated_at", "user_id", "admin_status", "total_price"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["bikes", "user"]
  end
end

app/models/review.rb
class Review < ApplicationRecord
  validates :review, presence: true, length: { maximum: 100 }
  belongs_to :user
  belongs_to :order

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "order_id", "review", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["order", "user"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_one :review
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/Profiles_Controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user! # Проверяет, что пользователь аутентифицирован, иначе перенаправляет на страницу входа

  def show
    @user_orders = current_user.orders
    @user = current_user
  end
end

app/controllers/chats_controller.rb
class ChatsController < InheritedResources::Base

  private

    def chat_params
      params.require(:chat).permit(:name, :number_phone, :status)
    end
end

app/controllers/feedback_controller.rb
class FeedbacksController < ApplicationController
  def create
    @feedback = Feedback.new(feedback_params)
    if @feedback.save
      # Обработка успешного сохранения
      redirect_to profile_path, notice: 'Ваша заявка успешно отправлена!'
    else
      # Обработка ошибок сохранения
      flash[:alert] = 'Произошла ошибка. Пожалуйста, попробуйте еще раз.'
      redirect_to pages_message_path, notice: 'Ваша заявка отклонена!' # Перенаправляем обратно на страницу контактов с ошибками
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:name, :phone_number)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # Ваш контроллер заказов (orders_controller.rb)

  def new
    @selected_bikes = params[:bikes].split(",") if params[:bikes].present?
    @order = Order.new
    @delivery_address = current_user.delivery_address if user_signed_in?
  end

  def extend
    @order = Order.find(params[:id])
    summ_bike = 0
    @order.bikes.each do |bike|
      summ_bike += bike.price
    end
    @order.update(end_date: @order.end_date + 1, total_price: @order.total_price + summ_bike)
    redirect_to profile_path
  end

  def create
    @order = Order.new(order_params.merge(bike_ids: params[:order][:bike_ids].split(",")))
    # Дополнительная обработка сохранения заказа
    if @order.save
      redirect_to profile_path, notice: 'Заказ успешно создан.'
    else
      render :new
    end
  end

 def cancel
  @order = Order.find(params[:id])

  # Обновляем статус велосипедов в зависимости от статуса заказа
  if @order.update(admin_status: 'cancel')
    @order.bikes.each do |bike|
      bike.update(status: :free)
    end

    redirect_to profile_path, notice: 'Заказ успешно отменен'
  else
    redirect_to profile_path, alert: 'Ошибка при отмене заказа'
  end
end


  private

  def review_params
    params.require(:review).permit(:review, :user_id)
  end

  def order_params
    params.require(:order).permit(:start_date, :end_date, :delivery_address, :return_address, :user_id, :status, :admin_status, :total_price, :bike_ids) # Включаем bike_ids
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @page_title = '| Велопрокат'
    @bikes = Bike.all
  end

  def delivery
    @page_title = '| Где кататься'
  end

  def message
    
  end

  def rules
    @page_title = '| Правила'
    @horizonts = Horizont.last(4).reverse # Получаем последние четыре объекта и переворачиваем порядок, чтобы отобразить их в порядке создания
  end

  def contacts
    @page_title = '| Контакты'
  end

  def about
    @page_title = '| О нас'
    @reviews = Review.last(3).reverse
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @order = Order.find(params[:order_id])
    @review = Review.new
  end

  def index
    @reviews = Review.all
  end

  def create
    @order = Order.find(params[:order_id])
    
    # Проверяем наличие отзыва для данного заказа
    if @order.review.present?
      redirect_to pages_message_path, alert: 'Нельзя оставлять более одного отзыва на один заказ'
      return
    end

    @review = @order.build_review(review_params)

    if @review.save
      redirect_to pages_message_path, notice: 'Отзыв успешно оставлен'
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:review, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BikePark <%= @page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= csrf_meta_tags %>

    <script src="https://kit.fontawesome.com/c29ac3ee6b.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
  </head>

  <body>

    <%= render 'layouts/shared/header' %>

    <main class="main">
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <%= render 'layouts/shared/footer' %>
    <%= render 'layouts/shared/popup' %>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<footer class="footer">
	<div class="container">
		<div class="footer-top">
			<span class="footer-span">Аренда велосипедов</span>
			<ul class="footer-menu">
				<li class="footer-menu__item">
					<a href="<%= pages_delivery_path %>" class="footer-menu__link">Правила</a>
				</li>

				<li class="footer-menu__item">
					<a href="<%= reviews_path  %>" class="footer-menu__link">Отзывы</a>
				</li>

				<li class="footer-menu__item">
					<a href="<%= pages_contacts_path %>" class="footer-menu__link">Контакты</a>
				</li>
			</ul>
		</div>
		<div class="footer-middle">
			<ul class="footer-middle-menu">
				<li class="footer-middle-menu__item">
					<a href="#" class="footer-middle-menu__link">Алюминий</a>
				</li>
				<li class="footer-middle-menu__item">
					<a href="#" class="footer-middle-menu__link">Карбон</a>
				</li>
				<li class="footer-middle-menu__item">
					<a href="#" class="footer-middle-menu__link">Горные/городские</a>
				</li>
				<li class="footer-middle-menu__item">
					<a href="#" class="footer-middle-menu__link">Городские эконом</a>
				</li>
			</ul>
		</div>
		<div class="footer-bottom">
			<span class="footer-copyright">© BikePark, 2024</span>
			<%# <a href="#" class="footer__link">Политика конфиденциальности</a> %>
			<ul class="footer-social-menu">
				<li class="footer-social-menu__item">
					<a href="#" class="footer-social-menu__link">
						<i class="fa-brands fa-vk"></i>
					</a>
				</li>
				<li class="footer-social-menu__item">
					<a href="#" class="footer-social-menu__link">
						<i class="fa-brands fa-telegram"></i>
					</a>
				</li>
			</ul>
		</div>
	</div>
</footer>

app/views/layouts/shared/_header.html.erb
<header class="header">
	<div class="container header-container">
		<nav class="navbar">
			<a href="<%= root_path %>" class="logo">
				<%= image_tag 'logo.svg', class: 'logo-img' %>
			</a>
			<ul class="menu">
				<li class="menu__item">
				  <a href="<%= pages_about_path %>" class="menu__link <%= 'active' if current_page?(pages_about_path) %>">О нас</a>
				</li>

				<li class="menu__item">
				  <a href="<%= root_path %>" class="menu__link <%= 'active' if current_page?(root_path) %>">Аренда</a>
				</li>

				<li class="menu__item">
				  <a href="<%= pages_delivery_path %>" class="menu__link <%= 'active' if current_page?(pages_delivery_path) %>">Правила</a>
				</li>

				<li class="menu__item">
				  <a href="<%= pages_rules_path %>" class="menu__link <%= 'active' if current_page?(pages_rules_path) %>">Где кататься</a>
				</li>

				<li class="menu__item">
				  <a href="<%= pages_contacts_path %>" class="menu__link <%= 'active' if current_page?(pages_contacts_path) %>">Контакты</a>
				</li>
			</ul>
		</nav>

		<ul class="action-menu">
			<li class="action-menu__item">
				<a href="tel: +79008009090" class="action-menu__link action-menu__phone">+79008009090</a>
			</li>

			<!-- <li class="action-menu__item">
				<a class="action-menu__link">
					<i class="fa-regular fa-user"></i>
				</a>
			</li> -->

			<li class="action-menu__item">
			  <% if user_signed_in? %>
			    <%= link_to profile_path, class: "action-menu__link-user" do %>
			      <i class="fa-solid fa-user-tie fa-user"></i>
			      <a class="action-menu__link-new"></a>
			      <!-- <i class="fa-regular fa-user fa-none"></i> -->
			    <% end %>
			  <% else %>
			    <a class="action-menu__link-new">
					<i class="fa-regular fa-user"></i>
				</a>
			  <% end %>
			</li>

			<li class="action-menu__item">
				<span class="button action-menu__button">
					Обратная связь
				</span>
			</li>

			<li class="action-menu__item">
				<div class="action-menu__time">
					<span class="menu-time">12:00</span><br>
					<span class="menu-time__place">Время в Волгодонске</span>
				</div>
			</li>

			
			<li class="action-menu__item_hide">
				<a href="#" class="action-menu__item_bars">
					<i class="fa-solid fa-bars"></i>
				</a>
			</li>
		</ul>
	</div>
</header>

<script>
	function updateTime() {
		let nowTime = new Date();
		let hoursNow = nowTime.getHours();
		let minutesNow = nowTime.getMinutes();

		hoursNow = hoursNow < 10 ? '0' + hoursNow : hoursNow;
		minutesNow = minutesNow < 10 ? '0' + minutesNow : minutesNow;

		let timeString = hoursNow + ':' + minutesNow;

		document.querySelector('.menu-time').innerHTML = timeString;
	}

	updateTime();
	setInterval(updateTime, 1000);
</script>

app/views/layouts/shared/_popup.html.erb
<section class="popup-wallpaper">
    <div class="popup-autorization popup">
        <div class="popup__header">
            <nav class="popup__header__navbar">
                <ul class="popup__header__menu">
                    <li class="popup__header__item active__popup-item popup__header__item_login">
                        Вход
                    </li> 
                    <li class="popup__header__item popup__header__item_register">
                        Регистрация
                    </li> 
                </ul>
                <a class="popup-form__close popup-form__close-profile">
                    <i class="fa-solid fa-circle-xmark"></i>
                </a>
            </nav>
        </div>
        <div class="popup__main">
          <%= form_for(User.new, as: :user, url: session_path(:user), html: { class: "popup-form" }) do |f| %>
            <label class="popup-form__phone-label popup-form-label">Логин*</label>
            <%= f.text_field :email, class: "popup-form__phone-input popup-form-input", placeholder: "Введите логин" %>
            <label class="popup-form__phone-label popup-form-label">Пароль*</label>
            <%= f.password_field :password, class: "popup-form__phone-input popup-form-input", placeholder: "Введите пароль" %>
            <%= f.submit "Войти", class: "popup-form__button button" %>
          <% end %>
        </div>


        <div class="popup__main-register">
          <%= form_for(User.new, url: registration_path(User), html: { class: "popup-form" }) do |f| %>
            <label class="popup-form__phone-label popup-form-label">Имя*</label>
            <%= f.text_field :name, class: "popup-form__phone-input popup-form-input", placeholder: "Введите имя" %>
            <label class="popup-form__phone-label popup-form-label">Логин*</label>
            <%= f.text_field :email, class: "popup-form__phone-input popup-form-input", placeholder: "Введите логин" %>
            <label class="popup-form__phone-label popup-form-label">Пароль*</label>
            <%= f.password_field :password, class: "popup-form__phone-input popup-form-input", placeholder: "Введите пароль" %>
            <div class="checkbox-box">
                <input class="contacts-form__checkbox" type="checkbox" id="check1" name="consentCheckbox">
                <label for="check1">Согласие на обработку персональных данных</label>
            </div>
            <%= f.submit "Регистрация", class: "popup-form__button button" %>
          <% end %>
        </div>

    </div>

    <div class="callback-popup popup">
        <div class="popup__header">
            <nav class="popup__header__navbar">
                <h2 class="title callbacl-popup__title">Есть вопросы? Оставьте номер, и мы всё обсудим</h2>
                <a class="popup-form__close popup-form__close-callback">
                    <i class="fa-solid fa-circle-xmark"></i>
                </a>
            </nav>
        </div>

        <div class="popup__main">
            <form class="popup-form">
                <input class="popup-form__phone-input popup-form-input" placeholder="Имя*">
                <input type="phone" class="popup-form__phone-input popup-form-input" placeholder="Номер телефона">
                <div class="checkbox-box">
                    <input class="contacts-form__checkbox" type="checkbox" id="check2" name="consentCheckbox">
                    <label for="check2">Согласие на обработку персональных данных</label>
                </div>
                <a class="popup-form__button button">Отправить</a>
            </form>
        </div>
    </div>
</section>

app/views/pages/about.html.erb
<section class="about-box">
	<section class="about section">
		<h1 class="title about__title">О нас <i class="fa-solid fa-users-viewfinder"></i></h1>

		<div class="about-box">
			<div class="about-box__text">
				<p class="about-box__p">
					Приветствуем вас в BikePark – вашем уголке велосипедных приключений! Мы – коллектив энтузиастов, объединенных любовью к велоспорту и активному образу жизни. BikePark не просто велопрокат; это история в каждой поездке, место, где каждый момент становится незабвенным впечатлением.
				</p>

				<p class="about-box__p">
					Наша команда – это союз опытных профессионалов, креативных дизайнеров и страстных велолюбителей. Мы создаем не просто велосипедные маршруты, а возможности освободиться от рутины и насладиться красотой окружающей природы на двух колесах.
				</p>

				<p class="about-box__p">
					BikePark предоставляет вам не просто велосипеды, а ключи к приключениям. Наши двухколесные компаньоны – это не просто средство передвижения, а способ раскрыть новые места и пережить невероятные впечатления.
				</p>

				<p class="about-box__p">
					Мы гордимся тем, что предлагаем широкий ассортимент велосипедов, подходящих для различных стилей езды и уровней подготовки. Вне зависимости от того, вы новичок или опытный райдер, у нас есть идеальный велосипед для ваших приключений.
				</p>

				<p class="about-box__p">
					Присоединяйтесь к нашему велосипедному сообществу, где каждый может поделиться своей страстью к велоспорту. Давайте создадим воспоминания, которые будут с вами всю жизнь. Педалируйте в будущее вместе с BikePark – местом, где каждая поездка – это новая история, каждый велосипед – ваш личный ключ к свободе и приключениям.
				</p>
			</div>
		</div>
	</section>
	<section class="about section">
	<h1 class="title about__title">Открытия <i class="fa-solid fa-spinner"></i></h1>

        <div class="about-box">
            <div class="about-box__text">
                <p class="about-box__p">
                    Для настоящих любителей велоспорта мы подготовили самые захватывающие маршруты, которые позволят вам полностью погрузиться в мир приключений и открытий. От легких прогулок по живописным местам до экстремальных трасс с захватывающими спусками — у нас есть маршрут для каждого велосипедиста.
                </p>

                <p class="about-box__p">
                    Наши профессиональные гиды поделятся с вами секретами и интересными фактами о местности, покажут самые красивые пейзажи и удивительные достопримечательности. Все маршруты разработаны с учетом ваших предпочтений и уровня подготовки, чтобы каждая поездка стала незабываемым приключением.
                </p>

                <p class="about-box__p">
                    Присоединяйтесь к нашим групповым или индивидуальным турам и откройте для себя новые уголки природы, ощутите адреналин от быстрой езды по горным склонам и насладитесь свежим воздухом и великолепными видами.
                </p>
            </div>
	</div>
</section>
</section>

<section class="reviews section">
	<h3 class="reviews-title">Отзывы <i class="fa-solid fa-envelope"></i></h3>
	<div class="reviews-box">
	  <% @reviews.each do |review| %>
	    <div class="reviews-box__block">
	      <p class="reviews__text">
	        <%= review.review %>
	      </p>
	      <span class="reviews__author">
	        <i class="fa-solid fa-fire"></i> <%= review.user.name %>
	      </span>
	    </div>
	  <% end %>
	</div>

	<a href="<%= reviews_path  %>" class="button button-reviews">Все отзывы</a>
</section>				

app/views/pages/contacts.html.erb
<section class="section contacts">
	<h1 class="contacts__title title">Контакты <i class="fa-solid fa-address-book"></i></h1>
	<div class="contacts-box">
		<div class="contacts-box-info">
			<div class="contacts-box-info__block">
				<span class="contacts-box-info__block-title contacts-title">Номер телефона</span>
				<p class="contacts-box-info__block-subtitle">+79008009090</p>
			</div>

			<div class="contacts-box-info__block">
				<span class="contacts-box-info__block-title contacts-title">E-mail</span>
				<p class="contacts-box-info__block-subtitle">info@bikerental.ru</p>
			</div>

			<div class="contacts-box-info__block">
				<span class="contacts-box-info__block-title contacts-title">Адрес</span>
				<p class="contacts-box-info__block-subtitle">Россия, Волгодонск, Новая 13</p>
			</div>
		</div>

		<form class="contacts-form" action="#">
			<span class="contacts-box-info__block-title contacts-title">Оставить заявку</span>
			<p class="contacts-form__subtitle">Остались вопросы? Свяжитесь с нами</p>
			<input type="text" class="contacts-form__input input" placeholder="Имя*">
			<input type="text" class="contacts-form__input input" placeholder="Номер телефона*">
			<label class="contacts-form__label" for="consentCheckbox" style="display: flex; align-items: center; 	margin: 25px 0;">
	            <input class="contacts-form__checkbox" type="checkbox" id="consentCheckbox" name="consentCheckbox">
	            <span class="contacts-form__checkbox-text">Согласие на обработку персональных данных</span>
	        </label>
			<button class="button contacts-form__button" type="submit">Отправить</button>
		</form>


	</div>
	<div class="contacts-map">
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5390.091007883136!2d42.14226118394924!3d47.5085050295047!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x411d4a8fac3bad39%3A0x829c45a1538b3631!2z0JLQvtC70LPQvtC00L7QvdGB0LosINCg0L7RgdGC0L7QstGB0LrQsNGPINC-0LHQuy4!5e0!3m2!1sru!2sru!4v1707914574865!5m2!1sru!2sru" width="100%" height="600px" style="border:0; border-radius: 10px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
	</div>
</section>

app/views/pages/delivery.html.erb
<section class="rules section">
	<h1 class="title rules__title">Правила <i class="fa-solid fa-circle-nodes"></i></h1>
	<div class="rules-conditions">
		<h2 class="rules-conditions__title">Условия аренды</h2>
		<div class="rules-conditions-box">
			<div class="rules-conditions__block">
				<h4 class="rules-conditions-title">Срок аренды</h4>
				<p class="rules-conditions__subtitle">Минимальный срок аренды велосипеда составляет 1 день. Однако, если вы планируете приключение более продолжительное, при бронировании от 5 дней действует приятная бонусная программа - скидка 10%. Это наше специальное предложение для тех, кто хочет наслаждаться велосипедными прокатами на полную катушку.</p>
			</div>

			<div class="rules-conditions__block">
				<h4 class="rules-conditions-title">Возврат и обмен</h4>
				<p class="rules-conditions__subtitle">Мы стремимся предоставить вам максимальное удовлетворение от аренды велосипеда. В случае необходимости изменения даты аренды или замены выбранного велосипеда на другой, свяжитесь с нашей службой поддержки. Мы готовы рассмотреть ваши запросы и найти оптимальное решение.</p>
			</div>

			<div class="rules-conditions__block">
				<h4 class="rules-conditions-title">Залог и ответственность</h4>
				<p class="rules-conditions__subtitle">При аренде велосипеда необходимо внести залог. Залог будет возвращен в полном объеме при возврате велосипеда в идеальном состоянии. Помните, что защита велосипеда в пути – это забота каждого арендатора. В случае утраты или повреждения велосипеда, мы обязуемся предоставить вам подробные инструкции по возмещению ущерба.</p>
			</div>
		</div>
	</div>

	<div class="rules-compensation">
		<h2 class="rules-compensation__title">Возмещение ущерба</h2>
		<p class="rules-compensation__subtitle">
			Мы понимаем, что в пути могут возникнуть непредвиденные ситуации. В случае возникновения ущерба велосипеду, будьте уверены, что мы предоставим вам подробные инструкции по действиям. Ваше комфортное путешествие - наша забота. Мы стремимся к прозрачным и честным отношениям, чтобы ваш опыт аренды велосипеда в BikePark был только приятным и незабвенным.
		</p>
	</div>
</section>

app/views/pages/message.html.erb
<section class="section">
    <% if flash[:notice].present? %>
        <div class="message-good message">
            <%= flash[:notice] %>
        </div>
    <% end %>

    <% if flash[:alert].present? %>
        <div class="message-bad message">
            <%= flash[:alert] %>
        </div>
    <% end %>

    <a href="<%= root_path %>" class="button button-back">На главную</a>
</section>

<script>
    // Перенаправление на главную страницу через 5 секунд
    setTimeout(function(){
        window.location.href = "<%= root_path %>";
    }, 5000);
</script>