config/routes.rb
Rails.application.routes.draw do
  resources :chats
  get 'reviews/new'
  get 'reviews/create'
  resources :orders, only: [:new, :create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { sessions: 'sessions' }
  root 'pages#home'
  get 'pages/delivery'
  get 'pages/rules'
  get 'pages/contacts'
  get 'pages/about'
  get 'pages/message'
  resources :feedback, only: [:create]

    # config/routes.rb
    resources :orders do
      member do
        patch 'cancel' # маршрут для отмены заказа
      end
    end

    # config/routes.rb
    resources :orders do
      member do
    get 'extend' # маршрут для продления заказа
  end
end

get 'reviews', to: 'reviews#index'

resources :orders do
  resource :review, only: [:new, :create]
end

get 'profile', to: 'profiles#show', as: :profile

end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/controllers/chats_controller.rb
class ChatsController < InheritedResources::Base

  private

    def chat_params
      params.require(:chat).permit(:name, :number_phone, :status)
    end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_chat.html.erb
<div id="<%= dom_id chat %>">
  <p>
    <strong>Name:</strong>
    <%= chat.name %>
  </p>

  <p>
    <strong>Number phone:</strong>
    <%= chat.number_phone %>
  </p>

</div>

app/views/chats/_form.html.erb
<%= form_with(model: chat) do |form| %>
  <% if chat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :number_phone, style: "display: block" %>
    <%= form.text_field :number_phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing chat</h1>

<%= render "form", chat: @chat %>

<br>

<div>
  <%= link_to "Show this chat", @chat %> |
  <%= link_to "Back to chats", chats_path %>
</div>

app/views/chats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Chats</h1>

<div id="chats">
  <% @chats.each do |chat| %>
    <%= render chat %>
    <p>
      <%= link_to "Show this chat", chat %>
    </p>
  <% end %>
</div>

<%= link_to "New chat", new_chat_path %>

app/views/chats/new.html.erb
<h1>New chat</h1>

<%= render "form", chat: @chat %>

<br>

<div>
  <%= link_to "Back to chats", chats_path %>
</div>

app/views/chats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @chat %>

<div>
  <%= link_to "Edit this chat", edit_chat_path(@chat) %> |
  <%= link_to "Back to chats", chats_path %>

  <%= button_to "Destroy this chat", @chat, method: :delete %>
</div>