config/routes.rb
Rails.application.routes.draw do
  resources :chats
  get 'reviews/new'
  get 'reviews/create'
  resources :orders, only: [:new, :create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { sessions: 'sessions' }
  root 'pages#home'
  get 'pages/delivery'
  get 'pages/rules'
  get 'pages/contacts'
  get 'pages/about'
  get 'pages/message'
  resources :feedback, only: [:create]

    # config/routes.rb
    resources :orders do
      member do
        patch 'cancel' # маршрут для отмены заказа
      end
    end

    # config/routes.rb
    resources :orders do
      member do
    get 'extend' # маршрут для продления заказа
  end
end

get 'reviews', to: 'reviews#index'

resources :orders do
  resource :review, only: [:new, :create]
end

get 'profile', to: 'profiles#show', as: :profile

end

app/models/order.rb
class Order < ApplicationRecord
  has_and_belongs_to_many :bikes
  belongs_to :user
  has_one :review

  enum admin_status: { in_processing: "В обработке", in_progress: "Выполняется", delivering: "Доставляется", completed: "Завершено", cancel: "Отменено" }
  enum status: { pay: "Оплачено", no_pay: "Не оплачено" }

  after_create :update_bike_status

  def update_bike_status
    self.bikes.each do |bike|
      if self.completed?
        bike.update(status: :free)
      else
        bike.update(status: :busy)
      end
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "delivery_address", "end_date", "id", "return_address", "start_date", "status", "updated_at", "user_id", "admin_status", "total_price"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["bikes", "user"]
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # Ваш контроллер заказов (orders_controller.rb)

  def new
    @selected_bikes = params[:bikes].split(",") if params[:bikes].present?
    @order = Order.new
    @delivery_address = current_user.delivery_address if user_signed_in?
  end

  def extend
    @order = Order.find(params[:id])
    summ_bike = 0
    @order.bikes.each do |bike|
      summ_bike += bike.price
    end
    @order.update(end_date: @order.end_date + 1, total_price: @order.total_price + summ_bike)
    redirect_to profile_path
  end

  def create
    @order = Order.new(order_params.merge(bike_ids: params[:order][:bike_ids].split(",")))
    # Дополнительная обработка сохранения заказа
    if @order.save
      redirect_to profile_path, notice: 'Заказ успешно создан.'
    else
      render :new
    end
  end

 def cancel
  @order = Order.find(params[:id])

  # Обновляем статус велосипедов в зависимости от статуса заказа
  if @order.update(admin_status: 'cancel')
    @order.bikes.each do |bike|
      bike.update(status: :free)
    end

    redirect_to profile_path, notice: 'Заказ успешно отменен'
  else
    redirect_to profile_path, alert: 'Ошибка при отмене заказа'
  end
end


  private

  def review_params
    params.require(:review).permit(:review, :user_id)
  end

  def order_params
    params.require(:order).permit(:start_date, :end_date, :delivery_address, :return_address, :user_id, :status, :admin_status, :total_price, :bike_ids) # Включаем bike_ids
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/extend.html.erb
<%= form_with(model: @order, url: extend_order_path(@order), method: :patch) do |form| %>
  <%= form.label :new_end_date, 'Новая дата окончания заказа:' %>
  <%= form.date_field :new_end_date %>
  <%= form.submit 'Продлить заказ' %>
<% end %>

app/views/orders/new.html.erb
<!-- app/views/orders/new.html.erb -->
<section class="section section-new-order">
	<h2 class="title section-new-order-title">Заявка на аренду велосипедов</h2>

	<%= form_with(model: @order, url: orders_path, param: '') do |form| %>
	  <% if @order.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@order.errors.count, "ошибка") %> заполнения формы:</h2>
	      <ul>
	      <% @order.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <!-- Вывод выбранных велосипедов -->
	  <ul class="bike-list">
		  	<% @summ = 0 %>
		    <% @selected_bikes.each do |bike_id| %>
		    	<li class="bike">
			      <% bike = Bike.find(bike_id) %>
			      <div class="park-section__block-img">
							<%= image_tag("bike.png") %>
						</div>
						<div class="park-section__block-text">
							<h3 class="park-section__block-text__title"><%= bike.title %></h3>
							<div class="park-section__block-text-info">
								<p class="park-section__block-text__price"><% @summ += bike.price %> <%= bike.price %> Рублей</p>
							</div>
						</div>
					</li>
		    <% end %>
	  </ul>

	  <div class="field-box">
	  	<div class="field">
			  <span class="field-span">Тип аренды</span>
			  <br>
			  <span class="field-span__ex">По дням</span>
			</div>

		  <div class="field">
			  <span class="field-span">Дата начала аренды</span>
			  <br>
			  <%= form.date_field :start_date, id: "start-date", value: Date.today, required: true %>
			</div>

			<div class="field">
			  <span class="field-span">Дата конца аренды</span>
			  <br>
			  <%= form.date_field :end_date, id: "end-date", required: true %>
			</div>
	  </div>

	  <div class="field-box">
			<div class="field">
			  <span class="field-span">Доставка</span>
			  <br>
			  <span class="field-span__ex">По адресу</span>
			</div>

			<div class="field">
		    <span class="field-span">Адрес доставки</span><br>
		    <% if user_signed_in? %>
				  <%= form.text_field :delivery_address, value: @delivery_address, class: 'field-span__ex', required: true %>
				<% else %>
				  <%= form.text_field :delivery_address, class: 'field-span__ex', required: true %>
				<% end %>
		  </div>

		  <div class="field">
		    <span class="field-span">Адрес возврата</span><br>
		    <% if user_signed_in? %>
				  <%= form.text_field :return_address, value: @delivery_address, class: 'field-span__ex', required: true %>
				<% else %>
				  <%= form.text_field :return_address, class: 'field-span__ex', required: true %>
				<% end %>
		  </div>
	  </div>

	<%#   <div class="field-label">
	  	<div class="field field-radio">
	  		<input type="radio" id="type_pay" name="drone" value="pay_place" checked />
    		<label for="type_pay">Оплата на месте</label>
	  	</div>
	  </div> %>

	  <!-- Общая сумма заказа -->
	  <div id="days-difference">Общая сумма заказа: 0</div>

	  <% @selecte_bikes = params[:bikes] %>

		<%= form.hidden_field :bike_ids, value: @selecte_bikes %>

	  <%= form.hidden_field :user_id, value: current_user.id %>
	  <%= form.hidden_field :status, value: "Не оплачено" %>
	  <%= form.hidden_field :admin_status, value: "in_processing" %>
	  <%= form.hidden_field :total_price, id: "total-price" %>


	  <div class="actions">
	    <%= form.submit "Забронировать", class: 'button button-order' %>
	  </div>
	<% end %>
</section>

<script>
	document.addEventListener("DOMContentLoaded", function() {
  const startDateInput = document.getElementById("start-date");
  const endDateInput = document.getElementById("end-date");

  startDateInput.addEventListener("change", function() {
    const startDate = new Date(startDateInput.value);
    const endDate = new Date(startDate);
    endDate.setDate(startDate.getDate() + 1);
    endDateInput.valueAsDate = endDate;
  });
});
</script>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const form = document.querySelector('form');
    const submitButton = form.querySelector('input[type="submit"]');

    form.addEventListener('submit', function(event) {
      // Проверяем валидность формы
      if (!form.checkValidity()) {
        // Если форма невалидна, предотвращаем отправку формы
        event.preventDefault();
        event.stopPropagation();
      }

      // Добавляем класс для отображения сообщений об ошибках
      form.classList.add('was-validated');
    });
  });
</script>


<script>
  document.addEventListener('DOMContentLoaded', function() {

    // Функция для расчета количества дней между датами
    function calculateDaysDifference() {
  // Получаем значения дат начала и окончания
  const startDate = new Date(document.getElementById('start-date').value);
  const endDate = new Date(document.getElementById('end-date').value);

  // Рассчитываем разницу в днях
  const differenceInTime = endDate.getTime() - startDate.getTime();
  const differenceInDays = Math.ceil(differenceInTime / (1000 * 3600 * 24));

  // Рассчитываем общую сумму
  const totalPrice = differenceInDays * <%= @summ %>;

  // Выводим результат
  document.getElementById('days-difference').innerText = 'Общая сумма: ' + totalPrice;

  // Записываем значение total_price в скрытое поле формы
  document.getElementById('total-price').value = totalPrice;
}


    // Вызываем функцию при изменении значений дат
    document.getElementById('start-date').addEventListener('change', calculateDaysDifference);
    document.getElementById('end-date').addEventListener('change', calculateDaysDifference);
  });

</script>