config/routes.rb
Rails.application.routes.draw do
  resources :chats
  get 'reviews/new'
  get 'reviews/create'
  resources :orders, only: [:new, :create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { sessions: 'sessions' }
  root 'pages#home'
  get 'pages/delivery'
  get 'pages/rules'
  get 'pages/contacts'
  get 'pages/about'
  get 'pages/message'
  resources :feedback, only: [:create]

    # config/routes.rb
    resources :orders do
      member do
        patch 'cancel' # маршрут для отмены заказа
      end
    end

    # config/routes.rb
    resources :orders do
      member do
    get 'extend' # маршрут для продления заказа
  end
end

get 'reviews', to: 'reviews#index'

resources :orders do
  resource :review, only: [:new, :create]
end

get 'profile', to: 'profiles#show', as: :profile

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @order = Order.find(params[:order_id])
    @review = Review.new
  end

  def index
    @reviews = Review.all
  end

  def create
    @order = Order.find(params[:order_id])
    
    # Проверяем наличие отзыва для данного заказа
    if @order.review.present?
      redirect_to pages_message_path, alert: 'Нельзя оставлять более одного отзыва на один заказ'
      return
    end

    @review = @order.build_review(review_params)

    if @review.save
      redirect_to pages_message_path, notice: 'Отзыв успешно оставлен'
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:review, :user_id)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/index.html.erb
<section class="section">
  <h2 class="title reviews-title">Все отзывы <i class="fa-solid fa-envelope"></i></h2>

  <div class="reviews-box-new">
      <% @reviews.each do |review| %>
      <div class="reviews-box-new__card">
        <p class="reviews__text">
          <%= review.review %>
        </p>
        <span class="reviews__author">
          <i class="fa-solid fa-fire"></i> <%= review.user.name %>
        </span>
      </div>
    <% end %>
  </div>
</section>

app/views/reviews/new.html.erb
<section class="section">
	<h2 class="title reviews-title">Оставить отзыв</h2>
	<%= form_with(model: @review, url: order_review_path(@order), method: :post) do |form| %>
	  <%= form.text_area :review, placeholder: 'Оставьте отзыв', class: 'review-text' %>

	  <%= form.hidden_field :user_id, value: current_user.id %><br>

	  <%= form.submit 'Оставить отзыв', class: "button review-button-click" %>
	<% end %>
</section>